version: '3.4'

services:
  sphagnum.debugclient:
    depends_on:
    - sphagnum.debugservice
    image: sphagnumdebugclient
    ports:
    - 5000:8080
    build:
      context: .
      dockerfile: Sphagnum.DebugClient/Dockerfile

  sphagnum.debugservice:
    hostname: test_server
    image: sphagnumdebugservice
    ports:
    - 5001:8080
    build:
      context: .
      dockerfile: Sphagnum.DebugService/Dockerfile

